# TODO API CI Pipeline

trigger:
  - master

pool:
  vmImage: "Ubuntu-16.04"

variables:
  buildConfiguration: "Release"

steps:
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: "**/*.csproj"
  - task: DotNetCoreCLI@2
    displayName: IntegrationTests
    inputs:
      command: test
      projects: "**/*IntegrationTests/*.csproj"
  - task: DotNetCoreCLI@2
    displayName: UnitTests
    inputs:
      command: test
      projects: "**/*UnitTests/*.csproj"
