# TODO API CI Pipeline

trigger:
  - master

pool:
  vmImage: "Ubuntu-16.04"

variables:
  buildConfiguration: "Release"

steps:
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: "**/*.csproj"
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: "**/*Tests/*.csproj"
      arguments: "--configuration $(buildConfiguration)"
