# TODO API CI Pipeline

trigger:
  - master

pool:
  vmImage: "Ubuntu-16.04"

variables:
  buildConfiguration: "Release"

steps:
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: dotnet build
      projects: "**/*.csproj"

script: dotnet test ~/IntegrationTests/IntegrationTests/IntegrationTests.csproj
script: dotnet test ~/UnitTests/UnitTests.csproj