# TODO API CI Pipeline

trigger:
  - master

pool:
  vmImage: "Ubuntu-16.04"

variables:
  buildConfiguration: "Release"

steps:
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: dotnet build
      projects: "**/*.csproj"
  - task: DotNetCoreCLI@2
    inputs:
      command: dotnet test ~/IntegrationTests/IntegrationTests/IntegrationTests.csproj
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: "**/UnitTests/*.csproj"
